### PR TITLE
simple python lib for emojione

### PR DESCRIPTION
**Pull request by kavirajk**
A python library for emojione

### CODE REVIEW

**Comment by mikebe11** [comment]
Thanks very much for putting this together. We appreciate the time and effort spent. We'll take a closer look at and get back to you. I'm afraid I can't say exactly when that'll be.

**Comment by mikebe11** [comment]
@kavirajk Finally got to running your tests. Got failures and errors. I'm running version 2.7.10
Aside from that it'd be preferable not to double up on assets in the whole package. Any spritesheets, css, mustache files, etc. that aren't unique should be linked to their equivalent in the assets folder.

**Comment by kavirajk** [comment]
Thanks for the time. Let me check with that version and let u know..



—
Kaviraj
Kaviraj.me

**Comment by kavirajk** [comment]
Added support for python 2.7. 
All test passes for python2.7 and python3.4

**Comment by mikebe11** [comment]
Sorry, it took a while to get to testing this. Thanks so much for the initial python library commit! We really appreciate the contribution.

**Pull request merged**
