### PR TITLE
Bump version of the Meteor package to 2.0.0

### PR DESCRIPTION
**Pull request by engelgabriel**

### CODE REVIEW

**Comment by engelgabriel** [comment]
Fixes this:
image

**Comment by engelgabriel** [comment]
@splendido how can we trigger the autopublish again?

**Comment by mikebe11** [comment]
@splendido I'm also wondering how we can trigger the autopublish again. During the last release (2.0.1) it wasn't triggered. I published that one manually.

**Comment by splendido** [comment]
@mikebe11 @engelgabriel sorry for the late reply.
I saw v2.1.0 was correctly triggered on autopublish (but then the build machine went timeout...) but failed. I manually retriggered the publish operation and got 'version already exists' which mean many different things to me:
* webhooks are still working
* meteor build machines took too much time to execute the publish operation (perhaps some update to meteor-tools yet to be done on the machine's image?) and I should probably raise a little the timeout limit..
* the publish process now got back to normal timings
* you already published the new version manually

Lets see what happens at the next release but I think it everything should be fine.
What do you think?

**Comment by mikebe11** [comment]
Hi @splendido I manually published this release. I wasn't sure if autopublish was working so I went ahead and did it. The next release will be left to autopublish and we'll see how it goes.

**Pull request merged**
