### PR TITLE
added title attribute for png based emojis - Fixes #280

### LINKED ISSUE #280: Using regular png emoji (not using sprite), the title attribute is missing
The png based emoji does not include a title attribute. There is an 'alt' attribute, but it's missing the title attribute. The title attribute is useful for when you don't know what an emoji means. You can hover your mouse over the emoji, and see a description. The alt attribute alone does not trigger the tooltip on mouse hover (I am using chrome).

### PR DESCRIPTION
**Pull request by charford**

### CODE REVIEW

**Comment by caseyahenson** [comment]
@charford Certainly a clean solution for adding the title attribute! Before I can merge this I'll need to update the testing files accordingly, and to make it a complete solution I think that adding an operator to make the title tag optional (probably off by default) will be a necessity, just in case it causes any issue with existing implementations.

You probably saw this Issue already but just in case, there is a good discussion on the title tag for this particular scenario: https://github.com/Ranks/emojione/issues/140.

**Comment by charford** [comment]
Thanks @caseyahenson for the feedback, makes sense. I went ahead and pushed an update to make this optional. By default it will work as it did before, but when setting pngTitleAttribute to true, it will include title attribute with png emoji. I had not seen that other issue, but it appears it's 8 months old. Let me know what else needs to be done here, if anything, so we can get these changes merged soon!

Thanks again,
Casey

**Comment by charford** [comment]
@caseyahenson anything I can do to get this merged?

**Comment by noahm** [comment]
I'd also like to see this addressed, but the current version of this PR only adds title attributes to one method of output. I would similarly like to see title attributes for images from ASCII smilies as well as image tags generated by the `unicodeToImage` function. (I have a fork of emojione where I have consolidated all the markup generation into a single function, and I plan to open a PR with it soon. If/when that is accepted making these sorts of changes will be a bit easier.)

**Comment by caseyahenson** [comment]
I made some updates to the Javascript and PHP libraries that generate an optional title attribute in the image tag. I'm going to close this pull request as it wasn't quite all encompassing but I do appreciate the work you did in getting the ball rolling on this!

**Pull request closed without merging**
