### PR TITLE
Add info about meteor support

### PR DESCRIPTION
**Pull request by qnub**
I've published metor package for emojione support https://atmospherejs.com/qnub/emojione and added here info about using.

### CODE REVIEW

**Comment by emitstop** [comment]
Cool, looks good from here. Thank you!

**Comment by engelgabriel** [comment]
Hi guys, any chance the Qnub could merge his changes back to the original project?

http://www.meteorpedia.com/read/Packaging_existing_Libraries
https://github.com/MeteorCommunity/discussions/issues/14

Thanks Qnub for the great packaging!

**Comment by engelgabriel** [comment]
Now many good libraries have their own official packdege

https://atmospherejs.com/?q=official

**Comment by mikebe11** [comment]
Hi engelgabriel,

Are you asking if we'd consider adding Qnub's Meteor integration into the repo?

**Comment by engelgabriel** [comment]
Yes, just the Meteor extra config files.

Considering the exponential growth of https://github.com/meteor/meteor it would be cool to have your offical packedege there, considering the such small effort.

**Comment by mikebe11** [comment]
The extra config files just the two starting with qnub:?

**Comment by engelgabriel** [comment]
but renaming it to emojione: as it would be the official version.. I can fork, do it, test it and send a PR if you say thats ok.

We are using your emojione at http://rocket.chat/

**Comment by mikebe11** [comment]
Great to see the meteor implementation in use.
If those are the config files then sure, feel free to submit a PR on it. We'll take a look at it and merge. Thanks!

**Comment by marceloschmidt** [comment]
Hey, we've just created PR #113 that adds emojione:emojione as official meteor package.

**Comment by engelgabriel** [comment]
:+1: accept please! :)

**Pull request merged**
