### PR TITLE
Update python ruleset

### PR DESCRIPTION
**Pull request by makario**
Regenerated the ruleset.py to match the updated emoji.json file. Also escaped unicode so the regex could handle `:asterisk:` properly. ~~Special-cased the `:asterisk:` emoji.~~

Also noticed that images would fail for some emoji (like `:hugging:`) due to being in all caps, so now images are generated using lowercase filenames.

### CODE REVIEW

**Comment by mikebe11** [comment]
Thanks a lot for this. We'll check it out soon an if all's good merge it.

**Comment by mikebe11** [comment]
For some reason I'm getting 9 errors with python 2.7.10 but tests pass on 2.7.6. I don't know python so do you have any idea why that is? Are your tests passing with python2.7 and python3.4?

**Comment by makario** [comment]
Interesting: mine are passing on both 2.7.10 and 3.4.3. Which tests are failing for you?

**Comment by makario** [comment]
(I just made a small change that I didn't notice before, but it shouldn't have any effect on the results of the tests.)

**Comment by mikebe11** [comment]
I'm getting `ValueError: unichr() arg not in range(0x10000) (narrow Python build)` on all the failures. A post online says you need to build python yourself with `./configure --enable-unicode=ucs4`. I don't know python so I don't doubt this is user error here. some failures:
test_emoji_at_end_of_sentence_with_alternate_punctuation
test_emoji_at_end_of_sentence_with_preceeding_colon
test_emoji_at_start_of_sentence
test_emoji_at_start_of_sentence_with_apostrophe

This is the preinstalled version provided by Apple. The v2.7.6 where everything passed was on a vagrant box.

**Comment by makario** [comment]
Ah, I see. Looks like Apple's preinstalled version of python is a narrow build, which uses two bytes per unicode character instead of four. I guess some of our emoji characters don't fit in that space. I wouldn't call that a user error on your part, though.

I don't have access to OS X at the moment, but I'll see if I whip up a solution the next time I'm around someone with a Mac.

In the meantime, if you're curious, you can check out these links:
http://wordaligned.org/articles/narrow-python
http://www.joelonsoftware.com/articles/Unicode.html

**Comment by makario** [comment]
All right, I added a work around. Can you verify that it works for you?

**Comment by mikebe11** [comment]
@makario Thanks for the article links. The one on the narrow build explained a lot.
Tests pass on Apple's pre-installed python 2.7.10. They also pass with my VM's python 2.7.6 and python 3.4.3, same vagrant box (ubuntu).
V3 took a bit of time to figure out. Needed to install setuptools then module six but it finally worked.

**Comment by makario** [comment]
:+1: thanks for persevering through that!

**Comment by mikebe11** [comment]
Thank you much for the update. Please feel free to contribute to the python library (or others) whenever you feel inclined to. We currently don't have much in the way of python support so it's very helpful.
Cheers

**Pull request merged**
