### PR TITLE
Added title attribute to images, improved Regex

### PR DESCRIPTION
**Pull request by cygery**
These commits were originally created for [RocketChat/Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) in [qnub/emojione](https://github.com/qnub/emojione) to fix RocketChat/Rocket.Chat#1245. Original PRs: qnub/emojione#2 and RocketChat/Rocket.Chat#1260.

### CODE REVIEW

**Comment by mikebe11** [comment]
Thanks for the submission. We'll be sure to take a closer look at this in the next day or so and get back to you on it.

**Comment by mikebe11** [comment]
I apologize for the time it took to review this PR. The upcoming collection has me busy lately.

I noticed one thing to start. `ns.shortnames` on line 8 was recently changed to allow for a little more compatibility with older versions of IE.

After some tests an issue with unicodeToImage came up. There's a chance that variable `mappedUnicode` can be undefined and that'll make variable `title` on line 327 undefined as well. When `ns.unicodeAlt = true` and `ns.sprites = false`

**Comment by cygery** [comment]
Thanks for your reply. I'll merge your recent changes soon and look into the other issue in more detail. Generally, it already exists in your current code (line 328), doesn't it? In that case, wouldn't a fallback to `ns.convert(unicode)` be sufficient?

**Comment by cygery** [comment]
I chose to fix the `mappedUnicode` issue by always defining it, i.e., unwrapping it from the surrounding if-clause. This would have been required to fix the undefined issue you described anyway (disregarding the other changes I made).

**Comment by mikebe11** [comment]
Thanks for the revision. Tough timing. We have the updated library being added with the new collection very soon. This probably won't make it in in time for that unless we can somehow squeeze it in. Either way we will review this again and see how it looks. Thanks

**Comment by mikebe11** [comment]
Ran some tests and for the most part this works but I'm afraid there's still an issue when running toImage() with `ns.imageType = 'svg'` and `ns.sprites = true` When hovering over the image the tooltip shows the shortname and then either the unicode character or shortname again, based on the the value of `ns.unicodeAlt`.  toShort() is running ns.unicodeToImage(str) which adds the title tag and shortname. Then it runs ns.shortnameToImage(str) which converts the title, nesting that svg tag inside the original title tag. So this isn't quite ready.
We've decided to pull back a little on adding the title attribute. It can still be added someday but it should be done thoroughly, in both PHP and JS libraries. Updated tests need to be included and it really should be an option based on a flag. It's a nice feature but not necessary everywhere. Users may not always desire this feature and it's not really useful for mobile.
If you'd like to take another crack at it you may want to propose a general plan here first. We know you've put plenty of time into it already and don't wish for you to waste your time on something that won't be merged.

**Comment by cygery** [comment]
Thanks for the update. I've currently neither the time nor the experience (esp. with PHP) to continue on this so I'll leave it open for somebody else who'd like to work on it.

**Comment by mikebe11** [comment]
Sounds good. I'm closing this PR since there's a title related issue already open.

**Pull request closed without merging**
