### PR TITLE
Fix #292 and #293

### LINKED ISSUE #292: Mixed similar categories
The `emoji.json` reports 67 definitions with category `food` and 18 with `foods`.

Also `pregnant_woman` has a `person` category (only emoji in that category), I guess it should be `people`.

### PR DESCRIPTION
**Pull request by Tymewalk**
Fixes #292 and #293 by adding proper categories.
In the case of #292, all "foods" were replaced with "food" and "person" was replaced with "people".

I edited the JSON using Python so if that caused any problems I can go back and redo it manually.

### CODE REVIEW

**Comment by Tymewalk** [comment]
Using Python decided to re-organize all the items. Which is probably not good.
Fixing by editing manually.

**Comment by Tymewalk** [comment]
OK, it's fixed now.

How do I verify the JSON to make sure it's not messed up?

**Comment by connorshea** [comment]
Bumping

**Comment by caseyahenson** [comment]
This issue should be resolved in the most recent emoji.json file update. Please submit an issue if you're still seeing categorization discrepancies.

**Comment by connorshea** [comment]
@caseyahenson thanks!

**Pull request closed without merging**
