### PR TITLE
Fix parse emojis for text ":P:smile:"

### PR DESCRIPTION
**Pull request by faytzel**

### CODE REVIEW

**Comment by mikebe11** [comment]
Thanks a lot for taking the time to submit the PR. We appreciate it. We'll take a look at it soon and get back to you with our thoughts.
btw, I know the build check failure was unrelated to your file change and has been fixed.

**Comment by faytzel** [comment]
okay, thank you very much :)

**Comment by mikebe11** [comment]
Thanks for being patient here. I ran some tests using benchmark.js  Results varied quite a bit between short test strings like `:P:smile:` and multiline strings.

>regexp x 141,882 ops/sec ±1.07% (88 runs sampled)
>shortnames array x 12,052 ops/sec ±0.71% (90 runs sampled)
>Fastest is regexp

>regexp x 48,490 ops/sec ±0.97% (91 runs sampled)
>shortnames array x 20,491 ops/sec ±0.85% (90 runs sampled)
>Fastest is regexp

Either way, looks like using the regular expression is the faster method. We're not saying no to your PR. Your method does work better with :P:smile: Even GitHub will parse that. Since your PR isn't for an issue that needs fixing right away I'm gonna leave this open for a bit for comments. If you or anyone else has any thoughts on feature vs. performance we're open to hearing them. Thanks

**Comment by mikebe11** [comment]
@faytzel Thanks for being patient here. I was about to merge your PR and noticed the js file is not the latest. The order of ns.emojioneList is reversed in the latest, starting with `:grinning:`.
Would you resubmit and I'll merge it? Thanks.

**Comment by faytzel** [comment]
Hi!!
I updated ns.emojioneList with the file https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js

Thanks you very much!!!

**Pull request merged**
