### PR TITLE
Refactoring PHP Code

### PR DESCRIPTION
**Pull request by Art4**
As planned in #24 this is a first step to refactoring the PHP code. There are still some open points on my todo list, like

- docs
- new tests / updating tests
- improve ClientInterface
- better config in Client

But I wanted to share my first steps so you can deside if this is a way you want to go. Also please check if you can update your generating script so you can build the `Ruleset.php` automatically. I'll be glad to hear your thoughts.

### CODE REVIEW

**Comment by Art4** [comment]
I must resolve the merge conflicts before this can be merged.

**Comment by Art4** [comment]
I've merged `master` and the changes from #100 and resolved all conflicts.

**Comment by mikebe11** [comment]
The new plan is interesting. We're certainly going to consider going with your idea/code. We'll need some time to review it and make that decision. One point mentioned here was about backwards compatibility. That's something we need to take into consideration. Once we get to looking at it we'll have a better idea going forward.
Again, thanks so much. These are great steps to look at and consider.

**Comment by kevinranks** [comment]
Hey @Art4, 

First of all I want to thank you for putting in the time here to contribute and improve the quality of the Emojione library. I went over your pull requests and your plan for refactoring again. I see where you're going with it but I'm struggling to see the real benefits. I don't really see anyone wanting to create their own client or ruleset implementations (maybe I'm wrong?). 

I'm having a hard time finding good reasons for so much separation. After all, this library was meant to help users convert emoji unicode characters into shortnames and then shortnames into our custom graphics. The way you're headed here makes it feel more like we're creating a multi-purpose replacement library.

Separating out the rules seems logical but I can't find a lot of good reasons for that either. Especially if we added the ability to let developers add their own custom replacements easily. Developers could also easily extend the Emojione class if they wanted to add additional behaviour without writing their own client. 

This is open for discussion, so let me know your thoughts. Thanks!

**Comment by Art4** [comment]
I'm planning to use Emojione in a project but I'm unhappy with the static class and `preg_replace_callback()` calls. I have also special ascii to shortname rules which only concerns my project.

I'd thought about building an adapter around the static class and using my own replace methods based on `str_replace()` for speed reasons. But instead of building my own adapter I want to share my code back in this project. After this PR it will be easier for me to extend the client and ruelset class and override the methods. So yes, I'm one user who wants to create a new client and ruleset. :smile:

> I'm having a hard time finding good reasons for so much separation. After all, this library was meant to help users convert emoji unicode characters into shortnames and then shortnames into our custom graphics. The way you're headed here makes it feel more like we're creating a multi-purpose replacement library.

Maybe you are right and this library should only contain the core replace functionalities. Methods like `$client->addShortcode()` should be not in this library and developers could extend the client class and implement their own methods. But I think this PR makes it easier for users/developers to extend the library and will be a benefit for the project.

**Comment by kevinranks** [comment]
I agree that moving away from the static class and having a magic method for backward compatibility to the static methods is a good idea. 

I also _do_ think it's a good idea to provide added functionality through new methods like ->addShortcodes(), ->addAscii(), etc. which would populate some additional replacement variables that would get run after the core methods.

For example:
```
public function shortnameToImage($string)
    {
          // replace emojione shortcode to image rules
          if(count($this->extra_shortnames) > 0) {
                    // if any additional user added shortnames rules exist, run those
          }

         if($this->ascii) {
                    // run emojione's ascii replacement rules
                    if(count($this->extra_ascii) > 0) {
                              // run additional ascii replacements if they exist
                    }
          }

          return $string;
    }
```
I believe that would allow developers to extend the class and override the default empty additional replacement vars so they wouldn't need to use the ->addShortcodes methods. 

Wouldn't this satisfy your needs while keeping library overall simpler? This would eliminate the need for a separate client & static loading the config vars.

Please let me know your thoughts, thanks!

**Comment by Art4** [comment]
It is better to program to an 'interface' than to an 'implementation'. If I would extend the class I would rather implement an interface or override a method than override an empty property. With your example I have to do this:

```php
class MyClient extends Client
{
    $extra_shortnames = array(
        ':crazy:' => '1f61c',
    );
}
```

But what if my shortnames come from an external source, like a config or database? Maybe I have to build a constructor than?

```php
class MyClient extends Client
{
    public function __construct()
    {
        // Get the shortnames from config or database or whatelse
        $this->extra_shortnames = \Config::get('extra_shortnames');
    }
}
```

But what if Client::__contruct() is already in use? Or will be in used in future? Than I have to implement some logic in my __constuct() method and have to take care for future changes in the library. I believe that this is not good design.

Another point against your idea: Your code have to check everytime for the $this->extra_shortnames property. This takes needless time for users who don't need the extra shortnames and don't extended the class.

I think an interface - like the `RulesetInterface` - is a better solution here. I can simply do this:

```php
class MyRuleset implements Emojione\RulesetInterface
{
    public function getAsciiReplace()
    {
        return array(
            ':crazy:' => '1f61c',
        );
    }

// other methods
}
```
or this:

```php
class MyRuleset extends Emojione\Ruleset
{
    public function getAsciiReplace()
    {
        $ascii = parent::getAsciiReplace();

        $ascii[':crazy:'] = '1f61c'

        return $ascii;
    }
}
```

and I don't have to care about the code or properties in the Client class as long as I'm implementing the interface. You on the other side can change your client code or property names and would not break any users code. And you don't have to check for properties that might be unused in most cases.

**Comment by kevinranks** [comment]
Hey @Art4, you make a good case for the Ruleset... but in your example wouldn't you still need to load your ASCII rules via the __construct of MyRuleset, which potentially brings in the same issue of having to override and/or run parent::__construct() ? 

This example doesn't make a case for why we should separate the Client out. I still don't see anyone needing or wanting to implement their own Client, especially if they can manipulate the ruleset easily. Do you agree with that?

**Comment by Art4** [comment]
> but in your example wouldn't you still need to load your ASCII rules via the __construct of MyRuleset, which potentially brings in the same issue of having to override and/or run parent::__construct() ? 

No, I wouldn't. `Client` class would only use the methods defined in `RulesetInterface` like this:

```php
    public function shortnameToImage($string)
    {
        // replace emojione shortcode to image rules
        // ...

        if($this->ascii)
        {
            $rules = $this->getRuleset()->getAsciiReplace();
            // run additional ascii replacements if they exist
        }

        return $string;
    }
```

so Ruleset::__construct() will never needed. As long as I'm using the `RulesetInterface` I can be sure, that `Ruleset::getAsciiReplace()` will return an array that I can extend.

> This example doesn't make a case for why we should separate the Client out.

What will be the alternative? Set all static and non-static methods in one class? As the `Emojione` class is a static flyweight for backward compatibility I wouldn't recommend to mix these classes. If we hadn't care about BC I would agree with you and simply delete the static `Emojione` class and rename `Client` to `Emojione` class. But we need BC, don't we?

A next plan for `Client` will be a better configuration through methods like `$client->useSprites(true);` instead of `$client->sprites = true;`.

> I still don't see anyone needing or wanting to implement their own Client, especially if they can manipulate the ruleset easily. Do you agree with that?

As I said in [this post](https://github.com/Ranks/emojione/pull/102#issuecomment-102688334) I planning to build my own replace methods based on `str_replace()` for speed reasons. I also know that I won't need the SVG files atm and I don't have to care about HTML in `$string` so perhaps I can modify my client like this:

```php
<?php

class MyClient extends Emojione\Client
{
	public function shortnameToImage($string)
	{
		$rules = $this->getRuleset()->getShortcodeReplace();

		$template = '<span class="emojione-%1$s" title="%2$s">%3$s</span>';

		$keys = array();
		$values = array();

		foreach ($rules as $unicode => $shortname)
		{
			$keys[] = $unicode;
			$values[] = sprintf($template, strtoupper($unicode), htmlspecialchars($shortname), $shortname);
		}

		return str_replace($keys, $values, $string);
	}
}
```

There are even more possibilities we don't know. But with easy expendable classes we make this library more interesting for developers. Maybe this library don't fit an special use case? No problem, just extend the client and move on.

**Pull request merged**
