### PR TITLE
Cleaner meteor packaging

### PR DESCRIPTION
**Pull request by splendido**
I've added a couple files to correctly handle `emojione` object export for Meteor.
This way there won't be problem even when the `emojione:emojione` package is used from inside another package.

### CODE REVIEW

**Comment by mikebe11** [comment]
hey @splendido   I was hoping to receive more opinions from others on your PR, particularly #146  I'm leaning towards passing on that one and merging the remainder of the commits in this PR instead. It's not because 146 is wrong in any way. I trust your experience with the platform. It far outweighs mine, but it seems like it'll sit there for a while waiting for others to chime in. And since it's not necessarily a patch but like you said, a preference, I'm thinking of staying closer to the current offering. Let me know if you've got any more thoughts on it. Thanks.

**Comment by splendido** [comment]
Makes sense @mikebe11!

**Comment by mikebe11** [comment]
All merged. Thanks again @splendido!

**Comment by engelgabriel** [comment]
@marceloschmidt @rodrigok @sampaiodiego and @qnub

What do you guys think about what @splendido proposed?

**Pull request closed without merging**
